stages:
  preprocess:
    cmd: python preprocess.py
    deps:
    - data.csv
    outs:
    - X_test_final.npy
    - X_train_final.npy
  train:
    cmd: python train.py
    deps:
    - preprocess.py
    outs:
    - model_results.joblib
  optimize:
    cmd: python train.py
    deps:
    - train.py
    outs:
    - best_model.joblib
