stages:
  preprocessing:
    cmd: python data_preprocessing.py
    deps:
      - data.csv
      - data_preprocessing.py
    outs:
      - preprocessed_data.csv

  train:
    cmd: model_training.py
    deps:
      - preprocessed_data.csv
      - model_training.py
    outs:
      - models/

