data:
  train_size: 0.8

preprocessing:
  numeric_features: ['area', 'num_rooms', 'num_bathrooms']
  categorical_features: ['location', 'type']
  
models:
  - name: LinearRegression
    hyperparameters:
      fit_intercept: true
  - name: RandomForestRegressor
    hyperparameters:
      n_estimators: 100
      max_depth: 10
  - name: GradientBoostingRegressor
    hyperparameters:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
